name: Test Orca Secrets action

on:
  workflow_dispatch:

jobs:
  secrets_scan_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan Secrets
        uses: ./
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "default"
          path:
            "test"
          format:
            "json"
          output:
            "results/"
          console_output: "table"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: orca-results
          path: results/
